### PR TITLE
Test fix: only load plone.app.contenttypes migration layer on Python 2.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This is needed to fix our failing test setup in combination with https://github.com/plone/plone.app.contenttypes/pull/641
That PR for Plone 6 removes the migration test layer.
Sample [failing test](https://jenkins.plone.org/job/pull-request-6.0-3.9/1136/testReport/junit/plone.app.linkintegrity.tests/test_circular/Startup/):

```
cannot import name 'PLONE_APP_CONTENTTYPES_MIGRATION_FIXTURE' from 'plone.app.contenttypes.testing' (/home/jenkins/workspace/pull-request-6.0-3.9/src/plone.app.contenttypes/plone/app/contenttypes/testing.py)

  File "/home/jenkins/.buildout/eggs/cp39/plone.app.linkintegrity-3.6.0-py3.9.egg/plone/app/linkintegrity/tests/test_circular.py", line 3, in <module>
    from plone.app.linkintegrity.testing import create
  File "/home/jenkins/.buildout/eggs/cp39/plone.app.linkintegrity-3.6.0-py3.9.egg/plone/app/linkintegrity/testing.py", line 3, in <module>
    from plone.app.contenttypes.testing import PLONE_APP_CONTENTTYPES_MIGRATION_FIXTURE  # noqa
```

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
Since master is used on 5.2 and 6.0, let's this this PR in isolation:

@jenkins-plone-org please run jobs
